server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456
  redis:
    database: 1
    host: 192.168.202.128
    port: 6379
    password: 111111

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl